
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation manual: !include automations.yaml
automation ems: !include_dir_merge_list ems/automations
script: !include scripts.yaml
script ems: !include ems/scripts.yaml
scene: !include scenes.yaml

template: !include ems/template_sensors.yaml
modbus: !include ems/modbus_gen24.yaml
utility_meter: !include ems/utility_meters.yaml
recorder: !include ems/recorder.yaml
input_boolean: !include ems/helpers_input_boolean.yaml
input_number:  !include ems/helpers_input_number.yaml
input_select:  !include ems/helpers_input_select.yaml
input_datetime: !include ems/helpers_input_datetime.yaml
